SHHTSystem/PinganHouse.SHHTS.UI.Web/Controllers/StaffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PinganHouse.SHHTS.DataTransferObjects;
using PinganHouse.SHHTS.Enumerations;
using PinganHouse.SHHTS.RemoteServiceProxy;
using PinganHouse.SHHTS.Utils.Log;
using PinganHouse.SHHTS.WebUI.Models;
using PinganHouse.SHHTS.WebUI.Filter;
using PinganHouse.SHHTS.WebUI.Helper;

namespace PinganHouse.SHHTS.WebUI.Controllers
{
    public class StaffController : Controller
    {
        [OAuth2QYFilter(AgentType.AgentCompany)]
        public ActionResult Index()
        {
            return View();
        }

        [OAuth2QYFilter(AgentType.AgentCompany)]
        public ActionResult List()
        {
            try
            {
                var staffName = Request["txtStaffName"];
                ViewData["staffName"] = staffName;
                var staffMobile = Request["txtStaffMobile"];
                ViewData["staffMobile"] = staffMobile;
                var identityNo = Request["txtIdentityNo"];
                ViewData["identityNo"] = identityNo;
                var totalCount = 0;
                if (identityNo == "") identityNo = null;
                if (staffMobile == "") staffMobile = null;

                IList<AgentStaff> agentStaffList = new List<AgentStaff>();
                string userId = UserHelper.GetAgentId();
                //string userId = "A153739130527606";
                var agency = AgentServiceProxy.GetAgentSatff(userId);
                long agentCompanySysNo = 0;
                if (agency != null)
                {
                    agentCompanySysNo = agency.AgentCompanySysNo;
                }
                agentStaffList = AgentServiceProxy.GetAgentStaffs(1, 10, out totalCount, agentCompanySysNo, null, staffName, identityNo,
                    null, staffMobile);

                ViewData["totalCount"] = totalCount;

                return View(agentStaffList);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return null;
            }
        }

        [OAuth2QYFilter(AgentType.AgentCompany)]
        public ActionResult GetAjaxList()
        {
            var model = new AjaxModel();
            try
            {
                int pageIndex = 0;
                int.TryParse(Request["pageIndex"], out pageIndex);
                var staffName = Request.Form["staffName"];
                var staffMobile = Request.Form["staffMobile"];
                var identityNo = Request.Form["identityNo"];
                if (identityNo == "") identityNo = null;
                if (staffMobile == "") staffMobile = null;

                var totalCount = 0;
                string userId = UserHelper.GetAgentId();
                var agency = AgentServiceProxy.GetAgentSatff(userId);

                var staffList = AgentServiceProxy.GetAgentStaffs(pageIndex, 10, out totalCount, agency.AgentCompanySysNo, null, staffName,
                    identityNo, null, staffMobile);
                model.data = staffList;
                model.hasError = false;
            }
            catch (Exception e)
            {
                model.hasError = true;
                model.error = e.Message;
            }
            return Json(model);
        }

        [OAuth2QYFilter(AgentType.AgentCompany)]
        public ActionResult Detail()
        {
            try
            {
                long staffNo = 0;
                long.TryParse(Request["id"], out staffNo);
                AgentStaff staff = AgentServiceProxy.GetAgentSatff(staffNo);
                if (staff.IsManager)
                {
                    ViewData["staffGrade"] = "管理者";
                }
                else
                {
                    ViewData["staffGrade"] = "员工";
                }
                AgentCompany company = AgentServiceProxy.GetAgentCompany(staff.AgentCompanySysNo);
                if (company!=null)
                { 
                    ViewData["companyName"] = company.CompanyName;
                    ViewData["staffName"] = Request["name"];
                    ViewData["staffMobile"] = Request["mobile"];
                    ViewData["identityNo"] = Request["identityNo"];
                    ViewData["staffIsManager"] = staff.IsManager;
                }

                string userId = UserHelper.GetAgentId();
                //string userId = "A153739130527606";
                var agency = AgentServiceProxy.GetAgentSatff(userId);
                ViewData["IsManager"] = agency.IsManager;
                return View(staff);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return null;
            }
        }

        [HttpPost, OAuth2QYFilter(AgentType.AgentCompany)]
        public ActionResult Delete()
        {
            var model = new AjaxModel();
            try
            {
                string userId = UserHelper.GetAgentId();
                //string userId = "A153739130527606";
                var agency = AgentServiceProxy.GetAgentSatff(userId);
                if (agency.IsManager)
                {
                    long sysNo = 0;
                    long.TryParse(Request["id"], out sysNo);

                    var result = AgentServiceProxy.DeleteStaff(sysNo, UserHelper.GetAgentId());
                    if (!result.Success)
                    {
                        model.hasError = true;
                        model.error = result.ResultMessage;
                    }
                    
                }
            }
            catch (Exception ex)
            {
                Log.Error(ex);

            }
            return Json(model);
        }

    }
}

SHHTSystem/PinganHouse.SHHTS.UI.Web/Views/Staff/Detail.cshtml
@{
    ViewBag.Title = "员工详情";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var staffModel = Model as PinganHouse.SHHTS.DataTransferObjects.AgentStaff;

}

<div class="esf-fd-calculator">

@*@using (Html.BeginForm("Delete", "Staff", FormMethod.Post))
{*@
    <div class="calculator-option">
        <dl>
            <dt>
                姓名
            </dt><dd>
                @(staffModel.RealName)
            </dd>
        </dl>
        <dl>
            <dt>
                手机号
            </dt><dd>
                @(staffModel.Mobile)
            </dd>
        </dl>
        <dl>
            <dt>
                身份证号
            </dt><dd>
                @(staffModel.IdentityNo)
            </dd>
        </dl>
        <dl>
            <dt>
                员工级别
            </dt><dd>
                @(ViewData["staffGrade"])
            </dd>
        </dl>
        <dl>
            <dt>
                公司全称
            </dt><dd>
                @(ViewData["companyName"])
            </dd>
        </dl>
    </div>

    <div class="calculator-btn">
        <input id="hidStaffName" type="hidden" value="@(ViewData["staffName"])" />
        <input id="hidStaffMobile" type="hidden" value="@(ViewData["staffMobile"])" />
        <input id="hidIdentityNo" type="hidden" value="@(ViewData["identityNo"])" />
        <input type="hidden" name="Id" id="hidSysNo" value="@(staffModel.SysNo)"/>
        @if (ViewData["IsManager"].ToString() == "True" && ViewData["staffIsManager"].ToString() == "False")
        {
            <button type="submit" class="btn-compute" id="J_Delete">删除员工信息</button>
        }
    </div>

@*}*@

</div>

  <!-- confirm -->
<div class="wxh-confirm-modal" style="display:none;" id="J_ConfirmModal" type="">
    <div class="wxh-confirm-modal-message" id="J_ConfirmMessage">员工的所有信息详情将被删除!</div>
    <div class="wxh-confirm-modal-button-bar basefix">
        <a class="button-confirm no" href="Javascript:void(0);" id="J_ConfirmNo">取消</a><em style="width:40px;display:inline-block;"></em>
        <a class="button-confirm yes" href="Javascript:void(0);" id="J_ConfirmYes">确认</a>
    </div>
</div>
<div class="wxh-confirm-modal" style="display:none;" id="J_ConfirmDeleteResult" type="">
    <div class="wxh-confirm-modal-message" id="J_ConfirmDeleteResultMessage" style="text-align: center"></div>
    <div class="wxh-confirm-modal-button-bar basefix">
        <a class="button-confirm yes" href="Javascript:void(0);" id="J_ConfirmDeleteResultYes">确认</a>
    </div>
</div>
<div class="masking" id="J_Mask"></div>

<script src="http://static.pinganfang.com/kissyui/1.3.2/build/kissy-min.js"></script>
<script src="http://static.pinganfang.com/kissyui/bui/adapter1.1.5-min.js"></script>
<script src="http://static.pinganfang.com/kissyui/config-min.js"></script>

<script>
    //KISSY.use("dom", function (S, DOM) {

    //    S.one('#btnDelete').on('click', function () {
    //        IO.Post("/Staff/Delete",{

    //        });

    //        //KISSY.use('io', function (S, IO) {
    //        //    // use IO
    //        //});

           



    //    });
    //});

    KISSY.use('ajax, event', function(S, IO, Event) {
        //Event.on('#J_Delete', 'click', function () {
        //    IO({
        //        url: '/Staff/Delete',
        //        type: 'post',
        //        data: {
        //            id: S.one("#hidSysNo").val()

        //        },
        //        success: function (data) {
        //            location.href = "/Staff/List?txtStaffName=" + S.one("#hidStaffName").val() + "&txtStaffMobile=" + S.one("#hidStaffMobile").val() + "&txtIdentityNo=" + S.one("#hidIdentityNo").val();
                    
        //        },
        //        error: function () {
        //            alert('error');
        //        }
        //    });
        //});

        // 展示
        Event.on('#J_Delete', 'click', function (e) {
            e.halt();
            S.one('#J_ConfirmModal').show();
            S.one('#J_Mask').show();
        });


        // 隐藏
        Event.on('#J_ConfirmNo', 'click', function () {
            S.one('#J_Mask').hide();
            S.one('#J_ConfirmModal').hide();
        });


        Event.on('#J_ConfirmDeleteResultYes', 'click', function () {
            S.one('#J_Mask').hide();
            S.one('#J_ConfirmDeleteResult').hide();
        });

        // 提交
        Event.on('#J_ConfirmYes', 'click', function () {
            S.one('#J_Mask').hide();
            S.one('#J_ConfirmModal').hide();
            // 如果是异步请求，那么这里就调用异步请求，如果不是就直接提交表单
            //S.one('#J_Submit').fire('click');
            IO({
                url: '/Staff/Delete?route=enterprise',
                        type: 'post',
                        data: {
                            id: S.one("#hidSysNo").val(),
                            route: "enterprise"

                        },
                        success: function (data) {
                            if (data.hasError == true) {
                                var errorMessate = data.error;
                                S.one('#J_ConfirmDeleteResultMessage').html(errorMessate);
                                S.one('#J_ConfirmDeleteResult').show();
                                S.one('#J_Mask').show();
                            } else {
                                location.href = "/Staff/List?route=enterprise&txtStaffName=" + S.one("#hidStaffName").val() + "&txtStaffMobile=" + S.one("#hidStaffMobile").val() + "&txtIdentityNo=" + S.one("#hidIdentityNo").val();
                            }
                        
                        },
                        error: function () {
                            alert('error');
                        }
                    });
        });

    });

    //KISSY.use('event', function (S, Event) {

    //    // 展示
    //    Event.on('#J_Delete', 'click', function (e) {
    //        e.halt();
    //        S.one('#J_ConfirmModal').show();
    //        S.one('#J_Mask').show();
    //    });


    //    // 隐藏
    //    Event.on('#J_ConfirmNo', 'click', function () {
    //        S.one('#J_Mask').hide();
    //        S.one('#J_ConfirmModal').hide();
    //    });

    //    // 提交
    //    Event.on('#J_ConfirmYes', 'click', function () {
    //        S.one('#J_Mask').hide();
    //        S.one('#J_ConfirmModal').hide();
    //        // 如果是异步请求，那么这里就调用异步请求，如果不是就直接提交表单
    //        S.one('#J_Submit').fire('click');
    //    });

    //});

</script>

SHHTSystem/PinganHouse.SHHTS.UI.Web/Views/Staff/Index.cshtml
@{
    ViewBag.Title = "员工搜索";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="esf-fd-calculator">

    @using (Html.BeginForm("List", "Staff", FormMethod.Get))
    {
        <div class="calculator-option">
            <dl>
                <input type="text" value="" class="input-txt-100" name="txtStaffName" placeholder="请输入员工姓名">
            </dl>
            <dl>
                <input type="text" value="" class="input-txt-100" name="txtStaffMobile" placeholder="请输入员工手机号">
            </dl>
            <dl>
                <input type="text" value="" class="input-txt-100" name="txtIdentityNo" placeholder="请输入员工身份证号码">
            </dl>
        </div>
    <input id="route" name="route" type="hidden" value="enterprise" />
        <div class="calculator-btn">
            <button tyep="submit" class="btn-compute">搜索</button>
        </div>

    }

</div>

<script src="http://static.pinganfang.com/kissyui/1.3.2/build/kissy-min.js"></script>
<script src="http://static.pinganfang.com/kissyui/bui/adapter1.1.5-min.js"></script>
<script src="http://static.pinganfang.com/kissyui/config-min.js"></script>

<script>

</script>

SHHTSystem/PinganHouse.SHHTS.UI.Web/Views/Staff/List.cshtml
@{
    ViewBag.Title = "员工列表";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var staffModelList = Model as IList<PinganHouse.SHHTS.DataTransferObjects.AgentStaff>;
}

<input id="hidStaffName" type="hidden" value="@(ViewData["staffName"])" />
<input id="hidStaffMobile" type="hidden" value="@(ViewData["staffMobile"])" />
<input id="hidIdentityNo" type="hidden" value="@(ViewData["identityNo"])" />

<div class="esf-transaction-schedule">
    <div class="search-field">
        <a href="/Staff/Index?route=enterprise" class="input-txt"><i class="iconfont">&#xe60a;</i>&nbsp;&nbsp;搜索员工</a>
    </div>

    <div class="total-info">
        <span class="txt">共有员工@(ViewData["totalCount"])人。</span>
    </div>

    <ul class="staff-list" id="J_StaffList">

        <li class="thead">
            <span class="name">姓名</span><span class="mobile">手机号&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
        </li>
        @{
            if (staffModelList != null)
            {
                foreach (var staff in staffModelList)
                {
                    <li class="tr J_TR">
                        <a href="/Staff/Detail?route=enterprise&id=@(staff.SysNo)&name=@(ViewData["staffName"])&mobile=@(ViewData["staffMobile"])&identityNo=@(ViewData["identityNo"])"><span class="name J_name">@(staff.RealName)</span><span class="mobile">@(staff.Mobile)</span><a href="javascript:void(0);" class="iconfont link J_Link">&#xe66a;</a></a>
                    </li>
                }
            }
        }


    </ul>

</div>



<script src="http://static.pinganfang.com/kissyui/1.3.2/build/kissy-min.js"></script>
<script src="http://static.pinganfang.com/kissyui/bui/adapter1.1.5-min.js"></script>
<script src="http://static.pinganfang.com/kissyui/config-min.js"></script>

<script>
    //是否正在请求
    var isLoading = false;
    //当前页面
    var pageIndex = 1;


    KISSY.use('ajax, event', function (S, IO, Event) {



        function getStaffData(pageIndex) {
            if (isLoading) {
                return;
            };
            IO({
                url: '/Staff/GetAjaxList?route=enterprise',
                type: 'post',
                dataType: "json",
                data: {
                    pageIndex: pageIndex + 1,
                    staffName: S.one("#hidStaffName").val(),
                    staffMobile: S.one("#hidStaffMobile").val(),
                    identityNo: S.one("#hidIdentityNo").val(),
                    route:"enterprise"

                },
                beforeSend: function () {
                    isLoading = true;
                },
                success: function (data) {
                    renderStaffList(data);
                    isLoading = false;
                },
                error: function () {
                    isLoading = false;
                }
            });
        }

        function renderStaffList(data) {
            var array = new Array();

            for (var k in data.data) {
                var html = [
                  '<li class="tr J_TR">',
                    '<a href="/Staff/Detail?route=enterprise&id='+ data.data[k].SysNo+'&name='+S.one("#hidStaffName").val()+'&mobile='+ S.one("#hidStaffMobile").val()+'&identityNo='+S.one("#hidIdentityNo").val()+'"><span class="name J_name">' + data.data[k].RealName + '</span><span class="mobile">' + data.data[k].Mobile + '</span><a href="javascript:void(0);" class="iconfont link J_Link">&#xe66a;</a></a>',
                  '</li>'
                ];
                array.push(html.join(''));
            }
            S.one('#J_StaffList').append(array.join(''));
            pageIndex += 1;

        }

        // 滚动到页底的时候请求数据
        Event.on(window, 'scroll', function () {
            var totalCount = @(ViewData["totalCount"]);
            var maxPage = Math.floor(totalCount / 5);
            if (totalCount % 5 > 0) maxPage += 1;

            if ((S.one(window).height() + S.one(window).scrollTop()) >= S.one("body").height()) {
                if (pageIndex< maxPage)
                {
                    getStaffData(pageIndex);
                }
            }
        });

    });




</script>