SHHTSystem/PinganHouse.SHHTS.UI.Web/Controllers/LoanCalculationController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PinganHouse.SHHTS.Enumerations;
using PinganHouse.SHHTS.RemoteServiceProxy;
using PinganHouse.SHHTS.Utils.Log;
using PinganHouse.SHHTS.WebUI.Models;

namespace PinganHouse.SHHTS.WebUI.Controllers
{
    public class LoanCalculationController : Controller
    {
        // GET: LoanCalculation
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult IndexZH()
        {
            return View();
        }

        public ActionResult Search()
        {
            try
            {
                var daiKuanLeiXing = Request.Form["hidDaiKuanLeiXing"];
                ViewData["daiKuanLeiXing"] = daiKuanLeiXing;
                double daiKuan = 0;    //贷款总额
                double.TryParse(Request.Form["txtDaiKuan"].ToString(), out daiKuan);
                ViewData["daiKuan"] = daiKuan;
                int anJieNianShu = 0;   //按揭年数
                int.TryParse(Request.Form["selAnJieNianShu"], out anJieNianShu);
                ViewData["anJieNianShu"] = anJieNianShu;
                double liLv = 0; //贷款利率
                double liLvZheKou = 0; //利率折扣
                double.TryParse(Request.Form["txtLiLv"], out liLv);
                double.TryParse(Request.Form["selLiLvZheKou"], out liLvZheKou);
                liLv = liLv * 0.01 * liLvZheKou;
                ViewData["liLv"] = liLv;
                string huanKuanFangShi = Request.Form["selHuanKuanFangShi"];
                ViewData["huanKuanFangShi"] = huanKuanFangShi;

                //贷款总额（元）
                ViewData["daiKuanYuan"] = daiKuan * 10000;
             
                if (daiKuanLeiXing != "zh")
                {

                    IList<LoanModel> moneyList = new List<LoanModel>();
                    if (huanKuanFangShi == "1")
                    {
                        var money = TotalMoney(anJieNianShu*12, daiKuan*10000, liLv);
                        moneyList = money.Item1;
                        ViewData["Interest"] = money.Item2;
                        ViewData["firstMonthMoney"] = money.Item3;
                    }
                    else
                    {
                        var money = MonthMoney(anJieNianShu*12, daiKuan*10000, liLv);
                        moneyList = money.Item1;
                        ViewData["Interest"] = money.Item2;
                        ViewData["firstMonthMoney"] = money.Item3;
                    }
                    IList<LoanModel> result = moneyList.Where(money => money.Year == 1).OrderBy(m => m.Month).ToList();


                    return View(result);
                }
                else
                {
                    double daiKuan_gjj = 0;    //贷款总额
                    double.TryParse(Request.Form["txtDaiKuan_gjj"].ToString(), out daiKuan_gjj);
                    ViewData["daiKuan_gjj"] = daiKuan_gjj;
                    int anJieNianShu_gjj = 0;   //按揭年数
                    int.TryParse(Request.Form["selAnJieNianShu_gjj"], out anJieNianShu_gjj);
                    ViewData["anJieNianShu_gjj"] = anJieNianShu_gjj;
                    double liLv_gjj = 0; //贷款利率
                    double liLvZheKou_gjj = 0; //利率折扣
                    double.TryParse(Request.Form["txtLiLv_gjj"], out liLv_gjj);
                    double.TryParse(Request.Form["selLiLvZheKou_gjj"], out liLvZheKou_gjj);
                    liLv_gjj = liLv_gjj * 0.01 * liLvZheKou_gjj;
                    ViewData["liLv_gjj"] = liLv_gjj;

                    IList<LoanModel> moneyList = new List<LoanModel>();

                    if (huanKuanFangShi == "1")
                    {
                        var money = TotalMoneyZH(anJieNianShu*12, daiKuan*10000, liLv, anJieNianShu_gjj*12, daiKuan_gjj*10000, liLv_gjj);
                        moneyList = money.Item1;
                        ViewData["Interest"] = money.Item2;
                        ViewData["firstMonthMoney"] = money.Item3;
                    }
                    else
                    {
                        var money = MonthMoneyZH(anJieNianShu*12, daiKuan*10000, liLv, anJieNianShu_gjj*12, daiKuan_gjj*10000, liLv_gjj);
                        moneyList = money.Item1;
                        ViewData["Interest"] = money.Item2;
                        ViewData["firstMonthMoney"] = money.Item3;
                    }

                    IList<LoanModel> result = moneyList.Where(money => money.Year == 1).OrderBy(m => m.Month).ToList();


                    return View(result);
                }



            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return null;
            }
        }


        public ActionResult GetLoanList()
        {
            var model = new AjaxModel();

            try
            {
                var daiKuanLeiXing = Request["daiKuanLeiXing"];
                int year = 0;
                int.TryParse(Request["year"], out year);
                double daiKuan = 0;    //贷款总额
                double.TryParse(Request["DaiKuan"], out daiKuan);
                int anJieNianShu = 0;   //按揭年数
                int.TryParse(Request["AnJieNianShu"], out anJieNianShu);
                double liLv = 0; //贷款利率
                double.TryParse(Request["LiLv"], out liLv);
                string huanKuanFangShi = Request["huanKuanFangShi"];

                if (daiKuanLeiXing != "zh")
                {
                    IList<LoanModel> moneyList = new List<LoanModel>();
                    if (huanKuanFangShi == "1")
                    {
                        moneyList = TotalMoney(anJieNianShu * 12, daiKuan * 10000, liLv).Item1;
                    }
                    else
                    {
                        moneyList = MonthMoney(anJieNianShu * 12, daiKuan * 10000, liLv).Item1;
                    }
                    IList<LoanModel> result =
                        moneyList.Where(money => money.Year == year).OrderBy(m => m.Month).ToList();

                    model.data = result;
                    model.hasError = false;
                }
                else
                {
                    double daiKuan_gjj = 0;    //贷款总额
                    double.TryParse(Request.Form["daiKuan_gjj"].ToString(), out daiKuan_gjj);
                    int anJieNianShu_gjj = 0;   //按揭年数
                    int.TryParse(Request.Form["anJieNianShu_gjj"], out anJieNianShu_gjj);
                    double liLv_gjj = 0; //贷款利率
                    double.TryParse(Request.Form["liLv_gjj"], out liLv_gjj);

                    IList<LoanModel> moneyList = new List<LoanModel>();

                    if (huanKuanFangShi == "1")
                    {
                        moneyList = TotalMoneyZH(anJieNianShu * 12, daiKuan * 10000, liLv, anJieNianShu_gjj * 12, daiKuan_gjj * 10000, liLv_gjj).Item1;
                    }
                    else
                    {
                        moneyList = MonthMoneyZH(anJieNianShu * 12, daiKuan * 10000, liLv, anJieNianShu_gjj * 12, daiKuan_gjj * 10000, liLv_gjj).Item1;
                    }
                    IList<LoanModel> result =
                        moneyList.Where(money => money.Year == year).OrderBy(m => m.Month).ToList();

                    model.data = result;
                    model.hasError = false;
                }
            }
            catch (Exception e)
            {
                model.hasError = true;
                model.error = e.Message;
            }

            return Json(model);
        }

        /// <summary>
        /// 方式：等额本金还款
        /// </summary>
        /// <param name="deadline">期限</param>
        /// <param name="money">总金额</param>
        /// <param name="dRate">年利率</param>
        /// <returns></returns>
        private Tuple<IList<LoanModel>,double,double> MonthMoney(int deadline, double money, double rate)
        {
            double[] sparePrin = new double[deadline];//剩余本金

            var principal = Math.Round(money / deadline, 0);
            double interest = 0;
            double firstMonthMoney = 0;

            IList<LoanModel> LoanModelList = new List<LoanModel>();
            for (int i = 0; i < deadline; i++)
            {
                var m = new LoanModel();
                m.Id = i + 1;
                m.Year = i / 12 + 1;
                m.Month = i % 12 + 1;
                m.Principal = principal;
                if (i == 0)
                {
                    sparePrin[i] = money - money / deadline;//剩余本金
                    if (sparePrin[i] < 0) sparePrin[i] = 0;
                    m.Interest = Math.Round(money * (rate / 12), 0);
                    interest += money * (rate / 12);
                    firstMonthMoney = m.Principal + money * (rate / 12);
                }
                else
                {
                    sparePrin[i] = sparePrin[i - 1] - money / deadline;//剩余本金
                    if (sparePrin[i] < 0) sparePrin[i] = 0;
                    m.Interest = Math.Round(sparePrin[i - 1] * (rate / 12), 0);
                    interest += sparePrin[i - 1] * (rate / 12);
                }
                m.Loan = Math.Round(sparePrin[i], 0);
                LoanModelList.Add(m);
            }

            return new Tuple<IList<LoanModel>, double, double>(LoanModelList, Math.Round(interest,0), Math.Round(firstMonthMoney,0));
        }

        /// <summary>
        /// 方式：等额本息还款
        /// </summary>
        /// <param name="deadline">期限</param>
        /// <param name="money">总金额</param>
        /// <param name="rate">年利率</param>
        /// <returns></returns>
        private Tuple<IList<LoanModel>, double,double> TotalMoney(int deadline, double money, double rate)
        {
            int i;
            double tlnAcct = 0, tdepAcct = 0;
            double interest = 0;
            double firstMonthMoney = 0;

SHHTSystem/PinganHouse.SHHTS.UI.Web/Views/LoanCalculation/Index.cshtml
@{
    ViewBag.Title = "房贷计算器";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="esf-fd-calculator">

    <div class="tab-title">
        <a class="item left-border-radius active" href="Javascript:void(0);">
            房贷计算器
        </a><a class="item right-border-radius" href="/TaxCalculation/Index">税费计算器</a>
    </div>

    <div class="loan-type">
        <div class="border">
            <a class="item left-border-radius" href="Javascript:void(0);" id="sydk">
                商业贷款
            </a><a class="item both-border" href="Javascript:void(0);" id="gjjdk">
                公积金贷款
            </a><a class="item right-border-radius" href="IndexZH">组合贷款</a>
        </div>
    </div>

@using (Html.BeginForm("Search", "LoanCalculation", FormMethod.Post))
{
    <div class="calculator-option">
        <dl>
            <dt>还款方式</dt><dd>
                <b></b>
                <select class="select-txt" name="selHuanKuanFangShi" id="selHuanKuanFangShi">
                    <option value="1" selected="selected">等额本息</option>
                    <option value="2">等额本金</option>
                </select>
                <i class="iconfont">&#xe66a;</i>
            </dd>
        </dl>
        <dl>
            <dt>贷款总额</dt><dd>
                <input type="tel" role="text-number" class="input-txt" name="txtDaiKuan" id="txtDaiKuan">
                <i>万元</i>
            </dd>
        </dl>
        <dl>
            <dt>贷款年数</dt><dd>
                <b></b>
                <select class="select-txt" name="selAnJieNianShu" id="selAnJieNianShu">
                    <option value="1">1年（12期）</option>
                    <option value="2">2年（24期）</option>
                    <option value="3">3年（36期）</option>
                    <option value="4">4年（48期）</option>
                    <option value="5">5年（60期）</option>
                    <option value="6">6年（72期）</option>
                    <option value="7">7年（84期）</option>
                    <option value="8">8年（96期）</option>
                    <option value="9">9年（108期）</option>
                    <option value="10">10年（120期）</option>
                    <option value="11">11年（132期）</option>
                    <option value="12">12年（144期）</option>
                    <option value="13">13年（156期）</option>
                    <option value="14">14年（168期）</option>
                    <option value="15">15年（180期）</option>
                    <option value="16">16年（192期）</option>
                    <option value="17">17年（204期）</option>
                    <option value="18">18年（216期）</option>
                    <option value="19">19年（228期）</option>
                    <option value="20">20年（240期）</option>
                    <option value="21">21年（252期）</option>
                    <option value="22">22年（264期）</option>
                    <option value="23">23年（276期）</option>
                    <option value="24">24年（288期）</option>
                    <option value="25">25年（300期）</option>
                    <option value="26">26年（312期）</option>
                    <option value="27">27年（324期）</option>
                    <option value="28">28年（336期）</option>
                    <option value="29">29年（348期）</option>
                    <option value="30" selected="selected">30年（360期）</option>
                </select>
                <i class="iconfont">&#xe66a;</i>
            </dd>
        </dl>
        <dl>
            <dt>利<b></b>率</dt><dd>
                <b></b>
                <select class="select-txt" name="selLiLvZheKou" id="selLiLvZheKou">
                    <option value="0.7">7折</option>
                    <option value="0.75">7.5折</option>
                    <option value="0.8">8折</option>
                    <option value="0.85">8.5折</option>
                    <option value="0.88">8.8折</option>
                    <option value="0.9">9折</option>
                    <option value="0.95">9.5折</option>
                    <option value="0.97">9.7折</option>
                    <option value="1" selected="selected">基准利率</option>
                    <option value="1.1">1.1倍</option>
                    <option value="1.5">1.5倍</option>
                </select>
                <i class="iconfont">&#xe633;</i>
                <input type="tel" role="text-number" value="5.4" class="input-txt" name="txtLiLv" id="txtLiLv">%
            </dd>
        </dl>
    </div>

        <div class="calculator-btn">
            <button tyep="submit" class="btn-compute">开始计算</button>
        </div>

}

</div>

<script src="http://static.pinganfang.com/kissyui/1.3.2/build/kissy-min.js"></script>
<script src="http://static.pinganfang.com/kissyui/bui/adapter1.1.5-min.js"></script>
<script src="http://static.pinganfang.com/kissyui/config-min.js"></script>

<script>
    var s;
    KISSY.use('uri', function (S, Uri) {
        var url = window.location.href;
        s = new Uri(url).getQuery().get('s')
       
        
    });

    KISSY.use("dom", function (S, DOM) {
        
        if (s == "gjj") {
            DOM.addClass("#gjjdk", "active");
            DOM.removeClass("#sydk", "active");
            S.one('#txtLiLv').val("3.5");
            S.one('#txtDaiKuan').val(50);
        } else {
            DOM.addClass("#sydk", "active");
            DOM.removeClass("#gjjdk", "active")
            S.one('#txtLiLv').val("5.4");
            S.one('#txtDaiKuan').val(100);
        }
        

        S.one('#gjjdk').on('click', function () {
            location.href = "/LoanCalculation/Index?s=gjj";
        });
        S.one('#sydk').on('click', function () {
            location.href = "/LoanCalculation/Index";
        });
    });
</script>

SHHTSystem/PinganHouse.SHHTS.UI.Web/Views/LoanCalculation/IndexZH.cshtml
@{
    ViewBag.Title = "房贷计算器";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="esf-fd-calculator">

    <div class="tab-title">
        <a class="item left-border-radius active" href="Javascript:void(0);">
            房贷计算器
        </a><a class="item right-border-radius" href="/TaxCalculation/Index">税费计算器</a>
    </div>

    <div class="loan-type">
        <div class="border">
            <a class="item left-border-radius" href="Index" id="sydk">
                商业贷款
            </a><a class="item both-border" href="Javascript:void(0);" id="gjjdk">
    公积金贷款
</a><a class="item active right-border-radius" href="Javascript:void(0);">组合贷款</a>
        </div>
    </div>
    @using (Html.BeginForm("Search", "LoanCalculation", FormMethod.Post))
    {
        <div class="calculator-option">
            <dl>
                <dt>还款方式</dt><dd>
                    <b></b>
                    <select class="select-txt" name="selHuanKuanFangShi" id="selHuanKuanFangShi">
                        <option value="1" selected="selected">等额本息</option>
                        <option value="2">等额本金</option>
                    </select>
                    <i class="iconfont">&#xe66a;</i>
                </dd>
            </dl>
            <dl>
                <dt>
                    商贷金额
                </dt><dd>
                         <input type="tel" role="text-number" value="100" class="input-txt" name="txtDaiKuan" id="txtDaiKuan">
                    <i>万元</i>
                </dd>
            </dl>
            <dl>
                <dt>
                    贷款年数
                </dt><dd>
                    <b></b>
                         <select class="select-txt" name="selAnJieNianShu" id="selAnJieNianShu">
                             <option value="1">1年（12期）</option>
                             <option value="2">2年（24期）</option>
                             <option value="3">3年（36期）</option>
                             <option value="4">4年（48期）</option>
                             <option value="5">5年（60期）</option>
                             <option value="6">6年（72期）</option>
                             <option value="7">7年（84期）</option>
                             <option value="8">8年（96期）</option>
                             <option value="9">9年（108期）</option>
                             <option value="10">10年（120期）</option>
                             <option value="11">11年（132期）</option>
                             <option value="12">12年（144期）</option>
                             <option value="13">13年（156期）</option>
                             <option value="14">14年（168期）</option>
                             <option value="15">15年（180期）</option>
                             <option value="16">16年（192期）</option>
                             <option value="17">17年（204期）</option>
                             <option value="18">18年（216期）</option>
                             <option value="19">19年（228期）</option>
                             <option value="20">20年（240期）</option>
                             <option value="21">21年（252期）</option>
                             <option value="22">22年（264期）</option>
                             <option value="23">23年（276期）</option>
                             <option value="24">24年（288期）</option>
                             <option value="25">25年（300期）</option>
                             <option value="26">26年（312期）</option>
                             <option value="27">27年（324期）</option>
                             <option value="28">28年（336期）</option>
                             <option value="29">29年（348期）</option>
                             <option value="30" selected="selected">30年（360期）</option>
                         </select>
                    <i class="iconfont">&#xe66a;</i>
                </dd>
            </dl>
            <dl>
                <dt>
                    利<b></b>率
                </dt><dd>
                    <b></b>
                         <select class="select-txt" name="selLiLvZheKou" id="selLiLvZheKou">
                             <option value="0.7">7折</option>
                             <option value="0.75">7.5折</option>
                             <option value="0.8">8折</option>
                             <option value="0.85">8.5折</option>
                             <option value="0.88">8.8折</option>
                             <option value="0.9">9折</option>
                             <option value="0.95">9.5折</option>
                             <option value="0.97">9.7折</option>
                             <option value="1" selected="selected">基准利率</option>
                             <option value="1.1">1.1倍</option>
                             <option value="1.5">1.5倍</option>
                         </select>
                    <i class="iconfont">&#xe633;</i>
                         <input type="tel" role="text-number" value="5.4" class="input-txt" name="txtLiLv" id="txtLiLv">%
                </dd>
            </dl>
            <dl>
                <dt>
                    公积金金额
                </dt><dd>
                         <input type="tel" role="text-number" value="50" class="input-txt" name="txtDaiKuan_gjj" id="txtDaiKuan_gjj">
                    <i>万元</i>
                </dd>
            </dl>
            <dl>
                <dt>
                    贷款年数
                </dt><dd>
                    <b></b>
                         <select class="select-txt" name="selAnJieNianShu_gjj" id="selAnJieNianShu_gjj">
                             <option value="1">1年（12期）</option>
                             <option value="2">2年（24期）</option>
                             <option value="3">3年（36期）</option>
                             <option value="4">4年（48期）</option>
                             <option value="5">5年（60期）</option>
                             <option value="6">6年（72期）</option>
                             <option value="7">7年（84期）</option>
                             <option value="8">8年（96期）</option>
                             <option value="9">9年（108期）</option>
                             <option value="10">10年（120期）</option>
                             <option value="11">11年（132期）</option>
                             <option value="12">12年（144期）</option>
                             <option value="13">13年（156期）</option>
                             <option value="14">14年（168期）</option>
                             <option value="15">15年（180期）</option>
                             <option value="16">16年（192期）</option>
                             <option value="17">17年（204期）</option>
                             <option value="18">18年（216期）</option>
                             <option value="19">19年（228期）</option>
                             <option value="20">20年（240期）</option>
                             <option value="21">21年（252期）</option>
                             <option value="22">22年（264期）</option>
                             <option value="23">23年（276期）</option>
                             <option value="24">24年（288期）</option>
                             <option value="25">25年（300期）</option>
                             <option value="26">26年（312期）</option>
                             <option value="27">27年（324期）</option>
                             <option value="28">28年（336期）</option>
                             <option value="29">29年（348期）</option>
                             <option value="30" selected="selected">30年（360期）</option>
                         </select>
                    <i class="iconfont">&#xe66a;</i>
                </dd>
            </dl>
            <dl>
                <dt>
                    利<b></b>率
                </dt><dd>
                    <b></b>
                         <select class="select-txt" name="selLiLvZheKou_gjj" id="selLiLvZheKou_gjj">
                             <option value="0.7">7折</option>
                             <option value="0.75">7.5折</option>
                             <option value="0.8">8折</option>
                             <option value="0.85">8.5折</option>
                             <option value="0.88">8.8折</option>
                             <option value="0.9">9折</option>
                             <option value="0.95">9.5折</option>
                             <option value="0.97">9.7折</option>
                             <option value="1" selected="selected">基准利率</option>
                             <option value="1.1">1.1倍</option>
                             <option value="1.5">1.5倍</option>
                         </select>
                    <i class="iconfont">&#xe633;</i>
                         <input type="tel" role="text-number" value="3.5" class="input-txt" name="txtLiLv_gjj" id="txtLiLv_gjj">%
                </dd>
            </dl>
        </div>

        <div class="calculator-btn">
            <button tyep="submit" class="btn-compute">开始计算</button><input type="hidden" name="hidDaiKuanLeiXing" value="zh"/>
        </div>

    }

</div>

<script src="http://static.pinganfang.com/kissyui/1.3.2/build/kissy-min.js"></script>
<script src="http://static.pinganfang.com/kissyui/bui/adapter1.1.5-min.js"></script>
<script src="http://static.pinganfang.com/kissyui/config-min.js"></script>

<script>
    KISSY.use("dom", function (S, DOM) {
        

        S.one('#gjjdk').on('click', function () {
            location.href = "/LoanCalculation/Index?s=gjj";
        });
        S.one('#sydk').on('click', function () {
            location.href = "/LoanCalculation/Index";
        });
    });
</script>