SHHTSystem/PinganHouse.SHHTS.UI.Web/Controllers/TaxCalculationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.Emit;
using System.Web;
using System.Web.Mvc;

namespace PinganHouse.SHHTS.WebUI.Controllers
{
    public class TaxCalculationController : Controller
    {
        // GET: TaxCalculation
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Result()
        {
            decimal area = 0;
            decimal price = 0;
            int priceType = 0;
            decimal originalPrice = 0;
            int houseType = 0;
            bool fiveYear;
            bool twoYear;
            bool first;
            bool onlyOne;

            decimal.TryParse(Request.Form["txtArea"], out area);
            decimal.TryParse(Request.Form["txtTotalPrice"], out price);
            price = price * 10000;

            string notarized = "";
            decimal loan = 0;
            string commissionedNotarized = "";

            decimal buyerTotal = 0;
            decimal sellerTotal = 0;

            int.TryParse(Request.Form["rdoPriceType"], out priceType);

            decimal.TryParse(Request.Form["txtOriginalPrice"], out originalPrice);
            originalPrice = originalPrice * 10000;

            int.TryParse(Request.Form["rdoHouseType"], out houseType);

            if (Request.Form["selYears"] == "1")
            {
                twoYear = false;
                fiveYear = false;
            }
            else if (Request.Form["selYears"] == "2")
            {
                twoYear = true;
                fiveYear = false;
            }
            else 
            {
                twoYear = true;
                fiveYear = true;
            }

            if (Request.Form["First"] == "on")
            {
                first = true;
            }
            else
            {
                first = false;
            }

            if (Request.Form["OnlyOne"] == "on")
            {
                onlyOne = true;
            }
            else
            {
                onlyOne = false;
            }


            if (Request.Form["Loan"] == "on")
            {
                decimal.TryParse(Request.Form["txtLoan"], out loan);
                loan = loan * 10000;
            }
            else
            {
                loan = 0;
            }


            //买方契税
            var deedTax = GetDeedTax(houseType, fiveYear, first, area, price);
            ViewData["DeedTax"] = deedTax.Item1.ToString("N");
            buyerTotal = buyerTotal + deedTax.Item1;

            //买方权证印花税
            var certificateStamDuty = GetCertificateStamDuty();
            ViewData["CertificateStamDuty"] = certificateStamDuty.Item1.ToString("N");
            buyerTotal = buyerTotal + certificateStamDuty.Item1;

            //买方登记费
            var registrationFee = GetRegistrationFee();
            ViewData["RegistrationFee"] = registrationFee.Item1.ToString("N");
            buyerTotal = buyerTotal + registrationFee.Item1;

            //买方图纸费
            var blueprintFee = GetBlueprintFee();
            ViewData["BlueprintFee"] = blueprintFee.Item1.ToString("N");
            buyerTotal = buyerTotal + blueprintFee.Item1;

            if (Request.Form["Loan"] == "on")
            {
                //买方抵押登记费
                var mortgageRegistrationFee = GetMortgageRegistrationFee();
                ViewData["MortgageRegistrationFee"] = mortgageRegistrationFee.Item1.ToString("N");
                buyerTotal = buyerTotal + mortgageRegistrationFee.Item1;
            }
            else
            {
                ViewData["MortgageRegistrationFee"] = "0.00";
            }

            //买方交易手续费
            var buyerTransactionFee = GetBuyerTransactionFee(area);
            ViewData["BuyerTransactionFee"] = buyerTransactionFee.Item1.ToString("N");
            buyerTotal = buyerTotal + buyerTransactionFee.Item1;


            if (Request.Form["Notarized"]=="on")
            {
                //公证费
                var notaryFee = GetNotaryFee(price);
                if (Request.Form["rdoNotarized"]=="1")
                {
                    //买方承担
                    ViewData["BuyerNotaryFee"] = notaryFee.Item1.ToString("N");
                    buyerTotal = buyerTotal + notaryFee.Item1;

                    ViewData["SellerNotaryFee"] = "0.00";
                }
                else if (Request.Form["rdoNotarized"] == "2")
                {
                    //卖方承担
                    ViewData["SellerNotaryFee"] = notaryFee.Item1.ToString("N");
                    sellerTotal = sellerTotal + notaryFee.Item1;

                    ViewData["BuyerNotaryFee"] = "0.00";
                }
                else if (Request.Form["rdoNotarized"] == "3")
                {
                    //卖买双方各半
                    ViewData["BuyerNotaryFee"] = (notaryFee.Item1 / 2).ToString("N");
                    buyerTotal = buyerTotal + (notaryFee.Item1 / 2);

                    ViewData["SellerNotaryFee"] = (notaryFee.Item1 / 2).ToString("N");
                    sellerTotal = sellerTotal + (notaryFee.Item1 / 2);

                }
                else
                {
                    //买方公证费
                    ViewData["BuyerNotaryFee"] = "0.00";
                    
                    //卖方公证费
                    ViewData["SellerNotaryFee"] = "0.00";
                }
            }
            else
            {
                //买方公证费
                ViewData["BuyerNotaryFee"] = "0.00";
               
                //卖方公证费
                ViewData["SellerNotaryFee"] = "0.00";
            }

            if (Request.Form["CommissionedNotarized"]=="on")
            {
                if (Request.Form["rdoCommissionedNotarized"]=="1")
                {
                    //买方委托公证费
                    var buyerCommissionedNotaryFee = GetBuyerCommissionedNotaryFee();
                    ViewData["BuyerCommissionedNotaryFee"] = buyerCommissionedNotaryFee.Item1.ToString("N");
                    buyerTotal = buyerTotal + buyerCommissionedNotaryFee.Item1;
                }
                else
                {
                    ViewData["BuyerCommissionedNotaryFee"] = "0.00";
                   
                }

                if (Request.Form["rdoCommissionedNotarized"] == "2")
                {
                    //卖方委托公证费
                    var sellerCommissionedNotaryFee = GetSellerCommissionedNotaryFee();
                    ViewData["SellerCommissionedNotaryFee"] = sellerCommissionedNotaryFee.Item1.ToString("N");
                    sellerTotal = sellerTotal + sellerCommissionedNotaryFee.Item1;
                }
                else
                {
                    ViewData["SellerCommissionedNotaryFee"] = "0.00";
                }

                if (Request.Form["rdoCommissionedNotarized"] == "3")
                {
                    //买方委托公证费
                    var buyerCommissionedNotaryFee = GetBuyerCommissionedNotaryFee();
                    ViewData["BuyerCommissionedNotaryFee"] = buyerCommissionedNotaryFee.Item1.ToString("N");
                    buyerTotal = buyerTotal + buyerCommissionedNotaryFee.Item1;

                    //卖方委托公证费
                    var sellerCommissionedNotaryFee = GetSellerCommissionedNotaryFee();
                    ViewData["SellerCommissionedNotaryFee"] = sellerCommissionedNotaryFee.Item1.ToString("N");
                    sellerTotal = sellerTotal + sellerCommissionedNotaryFee.Item1;
                }
                else
                {
                    ViewData["SellerCommissionedNotaryFee"] = "0.00";
                }
            }
            else
            {
                //买方委托公证费
                ViewData["BuyerCommissionedNotaryFee"] = "0.00";
                
                //卖方委托公证费
                ViewData["SellerCommissionedNotaryFee"] = "0.00";
            }



            if (Request.Form["Loan"]=="on")
            {
                if (Request.Form["LoanNotarized"]=="on")
                {
                    //买方贷款公证费
                    var creditNotarizationFee = GetCreditNotarizationFee(loan);
                    ViewData["CreditNotarizationFee"] = creditNotarizationFee.Item1.ToString("N");
                    buyerTotal = buyerTotal + creditNotarizationFee.Item1;
                }
                else
                {
                    ViewData["CreditNotarizationFee"] = "0.00";
                    
                }

                //买方贷款评估费
                var loanAssessmentFee = GetLoanAssessmentFee(price);
                ViewData["LoanAssessmentFee"] = loanAssessmentFee.Item1.ToString("N");
                buyerTotal = buyerTotal + loanAssessmentFee.Item1;
            }
            else
            {
                //买方贷款公证费
                ViewData["CreditNotarizationFee"] = "0.00";
                

                //买方贷款评估费
                ViewData["LoanAssessmentFee"] = "0.00";
                
            }

            //卖方营业税
            var sellerBusinessTax = GetSellerBusinessTax(houseType, twoYear, price, originalPrice);
            ViewData["SellerBusinessTax"] = sellerBusinessTax.Item1.ToString("N");
            sellerTotal = sellerTotal + sellerBusinessTax.Item1;

            //卖方个人所得税
            var sellerIncomeTax = GetSellerIncomeTax(priceType, fiveYear, houseType, onlyOne, price, originalPrice);
            ViewData["SellerIncomeTax"] = sellerIncomeTax.Item1.ToString("N");
            sellerTotal = sellerTotal + sellerIncomeTax.Item1;

            //卖方交易手续费
            var sellerTransactionFee = GetSellerTransactionFee(area);
            ViewData["SellerTransactionFee"] = sellerTransactionFee.Item1.ToString("N");
            sellerTotal = sellerTotal + sellerTransactionFee.Item1;

            ViewData["BuyerTotal"] = buyerTotal.ToString("N");
            
            ViewData["SellerTotal"] = sellerTotal.ToString("N");
            

            return View();
        }

SHHTSystem/PinganHouse.SHHTS.UI.Web/Views/TaxCalculation/Index.cshtml
@{
    ViewBag.Title = "税费计算器";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="esf-fd-calculator">

    <div class="tab-title">
        <a class="item left-border-radius " href="/LoanCalculation/Index">
            房贷计算器
        </a><a class="item right-border-radius active" href="Javascript:void(0);">税费计算器</a>
    </div>

@using (Html.BeginForm("Result", "TaxCalculation", FormMethod.Post))
{
    <div class="calculator-option">
        <dl>
            <dt>
                房屋面积
            </dt>
            <dd>
                <input type="tel" role="text-number" value="100" class="input-txt" name="txtArea">
                <i>平方米</i>
            </dd>
        </dl>
        <dl>
            <dt>
                房款总价
            </dt>
            <dd>
                <input type="tel" role="text-number" value="100" class="input-txt" name="txtTotalPrice">
                <i>万元</i>
            </dd>
        </dl>
        <dl>
            <dt>
                房屋原价
            </dt>
            <dd>
                <input type="tel" role="text-number" value="100" class="input-txt" name="txtOriginalPrice">
                <i>万元</i>
            </dd>
        </dl>
        <dl>
            <dt>
                计征方式
            </dt>
            <dd>
                <select class="select-txt" name="rdoPriceType" id="J_LevySelect">
                    <option value="1">总价</option>
                    <option value="2">差价</option>
                </select>
                <i class="iconfont">&#xe633;</i>
                @*<div class="hide" id="J_Levy">
                        <input type="text" value="100" class="input-txt" name="">
                        <i>万元</i>
                    </div>*@
            </dd>
        </dl>
        <dl>
            <dt>
                房屋性质
            </dt>
            <dd>
                <select class="select-txt" name="rdoHouseType">
                    <option value="1">&nbsp;&nbsp;&nbsp;&nbsp;普通住宅</option>
                    <option value="2">非普通住宅</option>
                </select>
                <i class="iconfont">&#xe633;</i>
            </dd>
        </dl>
        <dl>
            <dt>
                房产购置年限
            </dt>
            <dd>
                <select class="select-txt" name="selYears">
                    <option value="1">未满2年</option>
                    <option value="2">&nbsp;&nbsp;&nbsp;&nbsp;满2年</option>
                    <option value="3">&nbsp;&nbsp;&nbsp;&nbsp;满5年</option>
                </select>
                <i class="iconfont">&#xe633;</i>
            </dd>
        </dl>
        <dl>
            <dt>
                买方家庭首次购房
            </dt><dd>
                <span class="J_iOSTxt" style="display:block;margin-right:54px;">否</span>
                <label class="btn-ios-switch">
                    <input type="checkbox" class="ios-switch green J_iOSBtn" name="First" />
                    <div>
                        <div>
                        </div>
                    </div>
                </label>
            </dd>
        </dl>
        <dl>
            <dt>
                卖方家庭唯一住房
            </dt><dd>
                <span class="J_iOSTxt" style="display:block;margin-right:54px;">否</span>
                <label class="btn-ios-switch">
                    <input type="checkbox" class="ios-switch green J_iOSBtn" name="OnlyOne" />
                    <div>
                        <div>
                        </div>
                    </div>
                </label>
            </dd>
        </dl>
        <dl class="cat-tit">是否办理公证</dl>
        <dl>
            <dt>
                否
            </dt>
            <dd>
                <label class="btn-ios-switch">
                    <input type="checkbox" class="ios-switch green J_Checkbox" name="Notarized" data-item="Notarization" />
                    <div>
                        <div>
                        </div>
                    </div>
                </label>
            </dd>
        </dl>
        <dl class="hide J_Notarization">
            <dt>
                公证费承担主体
            </dt>
            <dd>
                <select class="select-txt" name="rdoNotarized">
                    <option value="1">买方</option>
                    <option value="2">卖方</option>
                    <option value="3">买卖双方各半</option>
                </select>
                <i class="iconfont">&#xe633;</i>
            </dd>
        </dl>
        <dl class="cat-tit">是否办理贷款</dl>
        <dl>
            <dt>
                否
            </dt>
            <dd>
                <label class="btn-ios-switch">
                    <input type="checkbox" class="ios-switch green J_Checkbox" name="Loan" data-item="Loan" />
                    <div>
                        <div>
                        </div>
                    </div>
                </label>
            </dd>
        </dl>
        <dl class="hide J_Loan">
            <dt>
                贷款金额
            </dt>
            <dd>
                <input type="text" value="100" class="input-txt" name="txtLoan">
                <i>万元</i>
            </dd>
        </dl>
        <dl class="hide J_Loan">
            <dt>
                是否办理贷款公证
            </dt>
            <dd>
                <label class="btn-ios-switch">
                    <input type="checkbox" class="ios-switch green" name="LoanNotarized" />
                    <div>
                        <div>
                        </div>
                    </div>
                </label>
            </dd>
        </dl>
        <dl class="cat-tit">是否办理委托公证</dl>
        <dl>
            <dt>
                否
            </dt>
            <dd>
                <label class="btn-ios-switch">
                    <input type="checkbox" class="ios-switch green J_Checkbox" name="CommissionedNotarized" data-item="Entrust" />
                    <div>
                        <div>
                        </div>
                    </div>
                </label>
            </dd>
        </dl>
        <dl class="hide J_Entrust">
            <dt>
                委托公证主体
            </dt>
            <dd>
                <select class="select-txt" name="rdoCommissionedNotarized">
                    <option value="1">买方</option>
                    <option value="2">卖方</option>
                    <option value="3">买方和卖方</option>
                </select>
                <i class="iconfont">&#xe633;</i>
            </dd>
        </dl>
    </div>

    <div class="calculator-btn">
        <button tyep="submit" class="btn-compute" id="J_BtnSubmit">开始计算</button>
    </div>

}

</div>

<div class="loading-v2" id="J_ShowLoading">
    <img src="http://file.pinganfang.com/view/banner/194ed5c0269740467ca2fdd0ebf5c2cd35f8fc5d.gif" class="icon-loading">
</div>

<script src="http://static.pinganfang.com/kissyui/1.3.2/build/kissy-min.js"></script>
<script src="http://static.pinganfang.com/kissyui/bui/adapter1.1.5-min.js"></script>
<script src="http://static.pinganfang.com/kissyui/config-min.js"></script>

<script>

    KISSY.use('ajax, event', function (S, IO, Event) {

        S.all('.J_Checkbox').removeAttr('checked');

        // 苹果开关变动的时候交互也要变动
        Event.on('.J_Checkbox', 'change', function () {
            var el = S.one(this);
            var item = el.attr("data-item");

            if (el.attr("checked") === "checked") {
                el.parent().parent().prev().text('是');
                S.all('.J_' + item).show();
            } else {
                el.parent().parent().prev().text('否');
                S.all('.J_' + item).hide();
            }
        });

        //Event.on('#J_LevySelect', 'change', function (e) {
        //    var el = S.one(this);
        //    if (el.val() === "2") {
        //        S.one('#J_Levy').css('display', "inline-block");
        //    } else {
        //        S.one('#J_Levy').hide();
        //    }
        //});

        // 菊花
        Event.on('#J_BtnSubmit', 'click', function () {
            S.one('#J_ShowLoading').show();
        });

        // 开关蚊子
        Event.on('.J_iOSBtn', 'change', function (e) {
            var el = S.one(this);
            if (el.attr("checked") === "checked") {
                el.parent().prev().text("是");
            } else {
                el.parent().prev().text("否");
            }
        });
    });

</script>

SHHTSystem/PinganHouse.SHHTS.UI.Web/Views/TaxCalculation/Result.cshtml
@{
    ViewBag.Title = "税费详情";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="fd-repayment-detail esf-fd-calculator">

    <div class="page-title">税费详情</div>

    <div class="tab-title">
        <a class="item left-border-radius active" href="Javascript:void(0);" id="aBuyer">
            买方
        </a><a class="item right-border-radius" href="Javascript:void(0);" id="aSeller">卖方</a>
    </div>

    <div class="calculator-option" id="dvBuyer">
        <div class="tit-item">
            <p class="tit-txt">
                税金总额
            </p>
            <p class="tit-price">
                <b class="font-size-18">@(ViewData["BuyerTotal"])元</b>
            </p>
        </div>
        <dl>
            <dt>
                契税
            </dt>
            <dd>
                @(ViewData["DeedTax"])元
            </dd>
        </dl>
        <dl>
            <dt>
                房产税
            </dt>
            <dd>
                0.00元
            </dd>
        </dl>
        <dl>
            <dt>
                权证印花税
            </dt>
            <dd>
                @(ViewData["CertificateStamDuty"])元
            </dd>
        </dl>
        <dl>
            <dt>
                登记费
            </dt>
            <dd>
                @(ViewData["RegistrationFee"])元
            </dd>
        </dl>
        <dl>
            <dt>
                图纸费
            </dt>
            <dd>
                @(ViewData["BlueprintFee"])元
            </dd>
        </dl>
        <dl>
            <dt>
                抵押登记费
            </dt>
            <dd>
                @(ViewData["MortgageRegistrationFee"])元
            </dd>
        </dl>
        <dl>
            <dt>
                交易手续费
            </dt>
            <dd>
                @(ViewData["BuyerTransactionFee"])元
            </dd>
        </dl>
        <dl>
            <dt>
                公证费
            </dt>
            <dd>
                @(ViewData["BuyerNotaryFee"])元
            </dd>
        </dl>
        <dl>
            <dt>
                委托公证费
            </dt>
            <dd>
                @(ViewData["BuyerCommissionedNotaryFee"])元
            </dd>
        </dl>
        <dl>
            <dt>
                贷款公证费
            </dt>
            <dd>
                @(ViewData["CreditNotarizationFee"])元
            </dd>
        </dl>
        <dl>
            <dt>
                贷款评估费
            </dt>
            <dd>
                @(ViewData["LoanAssessmentFee"] )元
            </dd>
        </dl>
    </div>

    <div class="calculator-option" id="dvSeller" style="display: none">
        <div class="tit-item">
            <p class="tit-txt">
                税金总额
            </p>
            <p class="tit-price">
                <b class="font-size-18">@(ViewData["SellerTotal"])元</b>
            </p>
        </div>

        <dl>
            <dt>营业税</dt>
            <dd>@(ViewData["SellerBusinessTax"])元</dd>
        </dl>
        <dl>
            <dt>个人所得税</dt>
            <dd>@(ViewData["SellerIncomeTax"])元</dd>
        </dl>
        <dl>
            <dt>交易手续费</dt>
            <dd>@(ViewData["SellerTransactionFee"])元</dd>
        </dl>
        <dl>
            <dt>公证费</dt>
            <dd>@(ViewData["SellerNotaryFee"])元</dd>
        </dl>
        <dl>
            <dt>委托公证费</dt>
            <dd>@(ViewData["SellerCommissionedNotaryFee"])元</dd>
        </dl>
    </div>

</div>

<script src="http://static.pinganfang.com/kissyui/1.3.2/build/kissy-min.js"></script>
<script>
    KISSY.use("dom", function (S, DOM) {
        //S.one('#dvBuyer').show();
        //S.one('#dvSeller').hide();

        S.one('#aBuyer').on('click', function () {
            S.one('#dvBuyer').show();
            S.one('#dvSeller').hide();
            DOM.addClass("#aBuyer", "active");
            DOM.removeClass("#aSeller", "active");
        });
        S.one('#aSeller').on('click', function () {
            S.one('#dvSeller').show();
            S.one('#dvBuyer').hide();
         
            DOM.addClass("#aSeller", "active");
            DOM.removeClass("#aBuyer", "active");
        });
    });
</script>